# Generated by Django 3.0.5 on 2020-06-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Coach', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evining')], default='M', max_length=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Player')),
            ],
        ),
    ]
