# Generated by Django 3.0.5 on 2020-06-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_choaching'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choaching',
            new_name='Coaching',
        ),
    ]
