# Generated by Django 3.0.5 on 2020-06-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200618_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coaching',
            new_name='Training',
        ),
    ]
