# Generated by Django 3.0.5 on 2020-06-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200618_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='Coach',
            new_name='coach',
        ),
    ]
