# Generated by Django 3.0.5 on 2020-06-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200619_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='coaches',
            field=models.ManyToManyField(to='main_app.Coach'),
        ),
    ]
